import{Dimensions} from 'react-native';
export const NEW_SCALE_RATIO = Dimensions.get('window').height / 500;
export const SCALE_RATIO = Dimensions.get('window').height / 1329;
export const MAIN_COLOR = '#00ace6';
export const EMPLOYERS_API = 'employers/api/';
export const OAUTH2_API = 'oauth2/api/';
export const CLIEN_ID = 'test';
export const SECRET = 'test';
export const SCALE_PADDING_OR_MARGIN = 1;
export const KEY_GOOGLE_MAP = 'AIzaSyBH3XpDDs01zBLosX1SRz7fHseqvFTW_XQ';
export const PUBLIC_API = 'public/api/';
export const MOBILE_API = 'mobileApp';
export const CANDIDATES_API = 'candidates/api/';
