export const strings = {
    search: 'Tìm Việc',
    testNN: 'Bài Test',
    skill: 'Kỹ Năng',
    course: 'Khóa Học',
    alert: 'Thông Báo',
    please_upgrade_to_a_new_version: 'Cập nhật phiên bản mới',
    update: 'Cập nhật',
    final_error_msg: 'Có lỗi xảy ra, vui lòng tắt ứng dụng và mở lại',
    access_token_expired: 'Access token hết hạn, vui lòng đăng nhập lại',
    your_role_is_not_allowed: 'Bạn không có quyền truy cập api này',
    notification: 'Thông Báo',
    login: 'Đăng nhập', 
    signup: 'Đăng ký', 
    forgot_pass: 'Quên mật khẩu', 
    no_account: 'Chưa có tài khoản?', 
    signin_fb: 'Đăng nhập với Facebook', 
    or: 'Hoặc',
    wrong_username_or_passowrd: 'Sai tên đăng nhập hoặc mật khẩu',
    morning: 'Ca Sáng',
    afternoon: 'Ca Chiều',
    evening: 'Ca Tối',
    wrong_email: 'Sai email hoặc email chưa đăng ký',
    internal_server_error: 'Có lỗi xảy ra',
    network_require_fail: 'Kết nối thất bại, vui lòng kiểm tra kết nối internet của bạn',
    nottfound: 'Không tìm thấy',
    main_func: 'Chức năng chính',
    other : 'Khác',
    logout : "Đăng xuất",
    share : ' Chia sẻ',
    change_pass: 'Đổi mật khẩu',
    acc : 'Tài khoản',
    review : 'Xem đánh giá',
    history : 'Lịch sử ứng tuyển',
    test : 'Test MBTI', 
    pass : 'Mật khẩu',
    forget_pass_2 : 'QUÊN MẬT KHẨU',
    verify_pass : 'Xác nhận đặt lại mật khẩu qua email',
    send : 'Gửi',
    check_email: 'Email đổi mật khẩu đã gửi thành công. Vui lòng kiểm tra email!',
    signUpSuccess: 'Vui lòng kiểm tra mail và xác nhận để tiếp tục đăng nhập!'
}